endpoints:
  hypermedia:
    enabled: true

info:
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @maven.compiler.source@
      target: @maven.compiler.target@
    project:
      name: '@project.name@'
      groupId: @project.groupId@
      artifactId: @project.artifactId@
      version: @project.version@

management:
  context-path: '/monitoring'
  port: 9001
  security:
    enabled: false
#    roles: 'ACTUATOR, SUPERUSER'

security:
  headers:
    cache: false
  user:
    name: admin
    password: secret

server:
  context-path: "/"
  port: 9000
  server-header: "@project.name@ v@project.version@"

spring:
  profiles:
    active: local

---

management:
  security:
    enabled: true

spring:
  profiles: PROD
  thymeleaf:
    cache: true