include: "https://raw.githubusercontent.com/dbmdz/development/master/ci/.gitlab-ci-base.yml"

variables:
  DOCKER_HOST: tcp://docker:2375/
  NO_PUBLISH: do_not_do_this

services:
- "$DIND_IMAGE"

.integration_tests:
  script:
  - mvn clean install -U
  - cd rest-webservice && mvn clean install -U
  - cd rest-integration-tests/src/test/resources/ && docker-compose up -d
  - sleep 10
  - cd ../../../../../ && mvn -B --projects rest-webservice/rest-integration-tests -Pintegration  surefire:test
  stage: test
  variables:
    REST_HOST: docker

integration_tests:
  extends: .integration_tests

integration_tests:openjdk11:
  extends: .integration_tests
  image: "$BUILD_IMAGE_ANSIBLE_MAVEN_JDK11"

.springboot_tests:
  script:
  - find ./webapp-springboot-thymeleaf/step* -maxdepth 0 -type d \( ! -name . \) -path ./webapp-springboot-thymeleaf/step14 -prune -o -exec bash -c "cd '{}' && pwd && mvn clean install -U" \;
  - find ./console-application-springboot/step* -maxdepth 0 -type d \( ! -name . \) -exec bash -c "cd '{}' && pwd && mvn clean install -U" \;

springboot_tests:
  extends: .springboot_tests

springboot_tests:openjdk11:
  extends: .springboot_tests
  image: "$BUILD_IMAGE_ANSIBLE_MAVEN_JDK11"
