management:
  endpoint:
    health:
      show-details: when-authorized
  endpoints:
    web:
      base-path: '/monitoring'
      exposure:
        include: "*"
  server:
    port: 9001
spring:
  security:
    user:
      name: admin
      password: secret
      roles: ENDPOINT_ADMIN