# Custom properties section START
custom:
  pathToUserProperties: classpath:users.properties

# Custom properties section END

spring:
  profiles:
    active: local

# Application info /info
info:
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @maven.compiler.source@
      target: @maven.compiler.target@
    project:
      name: '@project.name@'
      groupId: @project.groupId@
      artifactId: @project.artifactId@
      version: @project.version@

# mandatory configuration
jsondoc:
  basePath: http://localhost:9000
  version: 1.0
  packages[0]: de.digitalcollections.blueprints.rest.server.controller
  #packages[1]: com.example.model
  # optional configuration
  playgroundEnabled: true
  displayMethodAs: URI

management:
  endpoints:
    web:
      base-path: '/monitoring'
      exposure:
        include: "*"
  info:
    git:
      mode: full
  server:
    port: 9001

server:
  port: 9000
  server-header: "DigitalCollections Blueprint REST Server v@project.version@"

---

# PROD
custom:
  pathToUserProperties: file:///local/users.properties
  
jsondoc:
  basePath: https://www.myrestserver.com:9000

spring:
  profiles: PROD